### ISSUE TITLE
[Feature] Calendar Event Module

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_backend#20]
## Title

- [Feature] Calendar Event Module

## Description

- calendar에 이벤트에 대한 CRUD 가 가능한 Module 작성.

## TODO

- [x] : Event Service Interface 정의
- [x] : Event Entity 정의
- [x] : Event Service Interface 구현
- [x] : Event Module Controller API 작성
- [x] : TestCode 작성

## Watch out 

- 설계 후 해당 내용 Issue에 기록할 것

**Comment by leewoooo** [comment]
already resolved
