### ISSUE TITLE
[Feature] Notice API 수정

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_backend#28]
## Title

- Notice API 수정

## Description

- Notice API 수정이 필요
  - Created와 LastModified에 UserImage property 제거 (만약 삭제가 된 User라면 FE에 있는 기본 Image를 보여줄 것)
  - Notice Entity 수정 및 Response 수정
  - Notice를 조회할 때 Inner Join이 아닌 Left Join으로 수정 (User가 없을 경우 Notice가 조회되지 않는 경우가 발생)

## TODO

- [x] : Notice Entity 수정
- [x] : Notice 조회 시 Join 타입 변경
- [x] : Notice Response 수정
- [x] : Test Code 수정

## Watch out 

- Test Code를 작성할 때 의미 없는 Test Code를 작성하지 않을 것

**Comment by leewoooo** [comment]
already resolved with #30 PR
