### ISSUE TITLE
[Feature] Church Entity & Test environment

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_backend#4]
## Title

- Church Entity & Test environment

## Description

- 교회 entity 설계 및 test 환경 구축 (github ci + test container)

## TODO

- [x] : test container를 이용하여 test 환경 구축하기 + github action 설정하기
- [x] : church entity 설계
- [x] : church entity CRUD + test code

## Watch out 

- test container 를 이용하여 github action에서 테스트가 가능해야 한다.

**Comment by leewoooo** [comment]
already resolved with #6 PR
