### ISSUE TITLE
[Feature] 재적 관리

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_backend#5]
## Title

- Church, Family, Cell, User 재적 관리 구현

## Description

- 재적관리를 위한 Church, Family, Cell, User Entity 설계
- 연관 관계 Mapping 및 CRUD 작업 (Controller 작성 X)
- Test Container를 이용한 Test Code 작성 (e2e -> X) 

## TODO

- [x] : Church, Family, Cell. User 엔티티 설계 
- [x] : Church, Family, Cell. User User CRUD
- [x] : Test Container를 이용한 Test Code 작성 (성공, 실패 Case 작성 완료)

## Watch out 

- Controller, e2e Test는 진행하지 않음.

**Comment by leewoooo** [comment]
already resolved with #8 PR
