### ISSUE TITLE
[Feature] Migration Family To Group

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_backend#50]
## Title

- [Feature] Migration Family To Group

## Description

- Family Entity를 Group Entity로 마이그레이션
- Group Service를 정의할 때 Transactional 데코레이터 적용
- 주석 신경 쓸 것
- 테스트 코드 작성할 것

## TODO

- [x] : Entity명 변경 및 수정
- [x] : GroupService 정의 시 Transactional 데코레이터 적용
- [x] : GroupService에 주석 작성
- [x] : 테스트 코드 작성

## Watch out 

- enter text

**Comment by leewoooo** [comment]
already resolved with #49
