### ISSUE TITLE
[Feature] Apply Group to Cell Module

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_backend#51]
## Title

- [Feature] Apply Group to Cell Module

## Description

- Family를 Group으로 마이그레이션 하면서 변경점을 Cell Module에 적용 및 Cell Module 개선

## TODO

- [x] : Cell Module 요구명세서 작성
- [x] : 요구 명세서를 기반으로 Cell Module 개선 및 코드 작업
- [x] : 테스트 코드 작성

## Watch out 

- Cell Module 이 외 CI 빌드가 깨지는 부분을 무시할 것

**Comment by leewoooo** [comment]
## Create

- Cell의 이름은 Leader의 Name으로 정의 되기 때문에 Create요청 시 Name을 입력 받을 필요 없다.
- Cell을 등록할 때 Church, Group의 존재에 대한 Validation이 진행되어야 한다. 없을 경우 NotFoundException 
- Cell의 Leader의 Role을 CELL_LEADER로 변경되어야 한다. But 해당 User의 Role이 CELL_LEADER보다 높을 경우 변경하지 않음.

**Comment by leewoooo** [comment]
## List 조회

- Cell은 GroupId를 받아 해당 Group의 속한 Cell을 조회할 수 있어야 한다. (with paging)
- List를 조회할 때는 Leader와 같이 조회 될 필요가 없다

**Comment by leewoooo** [comment]
## Detail 조회

- Cell은  Id값을 받아 디테일을 조회할 수 있어야 한다.
- 디테일을 조회할 때 Leader와 같이 조회가 되어야 한다. (join 된 데이터)

**Comment by leewoooo** [comment]
## Update

- 새로운 리더가 존재하지 않으면 NotFoundException
- Leader가 변경되면 Leader를 하지 않는 다는 것으로 간주하여 해당 User의 Leader 자격을 박탈 및 Cell은 Null을 넣어주어 나중에 Cell이 Null인 User만 모아서 처리할 수 있도록 할 예정

**Comment by leewoooo** [comment]
## Delete

- 해당 Cell안에 User가 존재하는 경우 Cell을 삭제할 수 없음.
- Cell이 없어진다는 것은 해당 Cell의 Leader가 Leader를 하지 않는 다는 것으로 판단하여 Leader의 자격을 박탈

**Comment by leewoooo** [comment]
already resolved with #52 PR
