### ISSUE TITLE
[Feature] Apply Group to User Module

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_backend#53]
## Title

- [Feature] Apply Group to User Module

## Description

- Family를 Group으로 마이그레이션 하면서 변경점을 User Module에 적용 및 User Module 개선

## TODO

- [x] : User Module 요구명세서 작성
- [x] : 요구 명세서 기반으로 User Module 개선 및 코드작업
- [x] : 테스트 코드 작성

## Watch out 

- User 모듈이 완료되는 시점으로 CI가 깨지면 안된다.

**Comment by leewoooo** [comment]
## Create 

- User는 등록이 가능해야 한다.
- 새로 생길 User의 Role이 Leader 이상일 경우 Password는 존재해야 한다.
- 요청을 할 때 pycUser에서 ChurchID를 이용하여 Church의 존재 여부를 검사한다.
- RequestBody에 CellId가 있을 경우 Cell의 존재 여부를 검사한다.
- Name은 Church 안에서 중복될 수 없다.
- User를 등록할 때 image는 gravatar를 이용하여 초기값을 설정해준다.

**Comment by leewoooo** [comment]
## Read

- Name으로 FullText 검색이 가능해야 한다.
- ID를 통해 Detail을 조회할 수 있어야 한다.
- Token을 parsing하여 조회할 수 있어야 한다. (by UserId)
- Cell ID를 통해 조회가 가능해야 한다.
- Cell에 속하지 않은 User를 조회할 수 있어야 한다.

**Comment by leewoooo** [comment]
## Update

- Cell을 변경할 수 있어야 한다.
- Info를 변경할 수 있어야 한다. (age, rank, gender, birth, address, contact, isLongAbsence)

**Comment by leewoooo** [comment]
## Delete

- ID를 받아 User를 삭제할 수 있어야 하며 Soft Delete를 base로 한다.
- Role이 Leader 이상이면 삭제할 수 없다.

**Comment by leewoooo** [comment]
already resolved with #54
